### PR TITLE
Eclipse-related documentation and metadata updates

### PR DESCRIPTION
**Pull request by sergei-ivanov**
* Added the default m2e lifecycle mapping
* Updated README to include additional workarounds for Eclipse

### CODE REVIEW

**Comment by sergei-ivanov** [comment]
Supplementary notes:
This PR summarises various workarounds for Eclipse integration problems, as suggested by `protobuf-maven-plugin` community. Please see xolstice/protobuf-maven-plugin#10, xolstice/protobuf-maven-plugin#18, xolstice/protobuf-maven-plugin#41.

**Comment by szab100** [comment]
Tested, works like a charm!

**Comment by szab100** [comment]
Hey @sergei-ivanov, could you please add @trustin as a reviewer, so he might take a look when he has some time?

**Comment by sergei-ivanov** [comment]
I cannot appoint him as a reviewer, but he is the owner of the project and I am sure he is receiving these notifications. Please be patient: people are busy and some changes may take time.

**Comment by sergei-ivanov** [comment]
Related to #34

**Comment by trustin** [comment]
Sorry for getting late on this. Will check soon. Thanks for the head up!

**Comment by trustin** [comment]
Thanks a lot for your patience. Will release 1.6.1 today.

**Pull request merged**
