### PR TITLE
Add docs for os.name/os.arch mapping rules.

### PR DESCRIPTION
**Pull request by nmittler**

### CODE REVIEW

**Comment by nmittler** [comment]
@trustin PTAL

**Comment by nmittler** [comment]
@trustin ... gentle ping.  This should be an easy one ;)

**Comment by trustin** [comment]
@nmittler On my to-do list - will take care hopefully tomorrow.

**Comment by trustin** [comment]
@nmittler Updated [the `README.md` file](https://github.com/trustin/os-maven-plugin/blob/master/README.md). Please feel free to let me know if it needs an improvement.

**Comment by nmittler** [comment]
@trustin LGTM thanks!

**Comment by trustin** [comment]
I don't know why I thought this was not a PR but an issue! Sorry that I didn't merge this..

**Comment by nmittler** [comment]
@trustin haha, no worries buddy ... I like your change better :)

**Pull request closed without merging**
